#!/bin/tcsh
#
# start_questsrv_daytime
#
# start up the daytime questsrv program, which handles requests for
# dome status
#
# kill any running version
set l = `ps -aef | grep questsrv-daytime | grep -ve "grep" | grep -ve "start"`
if  ( $#l > 0 ) then
   kill -9 $l[2]
endif
cd /home/observer/logs
set d = `date +"%Y%m%d%H%M%S"`
set log =  questsrv_daytime.$d.log
date >! $log
echo "starting questsrv-daytime.pl" >> $log
~/bin/questsrv-daytime.pl >>& questsrv_daytime.$d.log &

